<?php

$title = 'Artikel';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>">Erstelle einen neuen Artikel</a>
</p>

<table class="table">
<tr>
    <th>Titel</th>
    <th>Text</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($blogs as $blog) : ?>
    <tr>
        <td><?= $this->escapeHtml($blog->title) ?></td>
        <td><?= $this->escapeHtml($blog->text) ?></td>
        <td>
            <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $blog->id]) ?>">Edit</a>
            <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $blog->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>